name: webapproval

on:
  pull_request:
    types: labeled
    branches: [ main ]

jobs:
  webapproval:
    runs-on: ubuntu-latest
    steps:
      - name: fail check unless labeled with webapproval
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'webapproval') }}
        uses: cutenode/action-always-fail@v1.0.1
      - name: record web approval via cdlib-cli
        if: contains(github.event.pull_request.labels.*.name, 'webapproval')
        uses: addnab/docker-run-action@v3
        with:
          image: cdlib-cli:5.latest
          run: cdlib webapproval record blablub
          registry: docker.artifactory.xhl.com
          username: srv_cdlib
          password: secret
