name: webapproval

on:
  pull_request:
    types: labeled
    branches: [ main ]

jobs:
  webapproval:
    if: contains(github.event.pull_request_labels.*.name, 'webapproval')
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run Action
        uses: addnab/docker-run-action@v3
        with:
          image: cdlib-cli:5.latest
          run: cdlib webapproval record blablub
          registry: docker.artifactory.xhl.com
          username: srv_cdlib
          password: secret
